[build]
  command = "npm run build:netlify"
  publish = "dist/surya-portfolio/browser"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"
