[build]
  command = "npm run build"
  publish = "dist/surya-portfolio/browser"  # ‚Üê Change this!
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "24.13.0"

[[plugins]]
  package = "@netlify/angular-runtime"
